---
- name: Preconfig block
  become: true
  hosts: demo
  tasks:
    - name: Установка Docker
      block:
        - name: Добавляем universe
          ansible.builtin.apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present

    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update-cache: true
        cache_valid_time: 86400

    - name: Добавление ключа Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}
          stable
        state: present
        update_cache: true
        filename: docker

    - name: Установка Docker-ce
      ansible.builtin.apt:
        name: docker-ce
        update_cache: true

    - name: Проверка что модуль установлен и перезагружен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: Установка Docker-compose
      block:
        - name: Получение последней версии Docker-compose
          ansible.builtin.uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Установка Docker-compose
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: '0755'

    - name: Завершение установки
      block:
        - name: Добавление пользователя в группу docker
          ansible.builtin.user:
            name: '{{ ansible_user }}'
            groups: docker
            append: true
        - name: Перезагрузка сервера
          ansible.builtin.reboot:
